name: Build Python Project

on:
  push:
    branches:
      - main
  pull_request:

jobs:
#  build-linux:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Set up Python
#        uses: actions/setup-python@v4
#        with:
#          python-version: "3.11"
#
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install pyinstaller requests
#
#      - name: Build Linux binary
#        run: |
#          pyinstaller --onefile --add-binary "tools/linux/wg:tools/linux" --add-binary "tools/linux/wg-quick:tools/linux" main.py --exclude-module tkinter --exclude-module sqlite3 --exclude-module unittest --exclude-module email --exclude-module html --exclude-module http --exclude-module imaplib --exclude-module json --exclude-module multiprocessing --exclude-module pydoc  --exclude-module ssl --exclude-module urllib --exclude-module xml --exclude-module xmlrpc --exclude-module wsgiref --exclude-module logging --exclude-module argparse --exclude-module gzip --exclude-module bz2 --exclude-module lzma --exclude-module cgi --exclude-module http --exclude-module email --exclude-module socketserver --exclude-module ipaddress --exclude-module code --exclude-module site --exclude-module getopt --exclude-module difflib --exclude-module tokenize --exclude-module readline --exclude-module tracemalloc --exclude-module calendar --exclude-module getpass --exclude-module locale --exclude-module inspect --exclude-module warnings --exclude-module contextlib --exclude-module types --exclude-module importlib --exclude-module pkgutil --exclude-module zipfile --exclude-module shutil --exclude-module tempfile --exclude-module enum --exclude-module fnmatch --exclude-module filecmp --exclude-module pathlib --exclude-module secrets --exclude-module pprint
#
#      - name: Upload Linux binary
#        uses: actions/upload-artifact@v4
#        with:
#          name: linux-binary
#          path: dist/main
#
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller requests

      - name: Build Windows binary
        run: |
          pyinstaller --onefile --add-data "tools/windows/wg.exe;tools/windows" main-win.py 
      - name: Upload Windows binary
        uses: actions/upload-artifact@v4
        with:
          name: windows-binary
          path: dist/main-win.exe
