name: Build Python Project

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Create clean virtualenv
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install pyinstaller requests

      - name: Build Linux binary
        run: |
          source venv/bin/activate
          pyinstaller --onefile --add-binary "tools/linux/wg:tools/linux" --add-binary "tools/linux/wg-quick:tools/linux" main.py
          # Compress + strip
          strip dist/main
          upx --best dist/main || echo "UPX not installed, skipped"

      - name: Upload Linux binary
        uses: actions/upload-artifact@v4
        with:
          name: linux-binary
          path: dist/main

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Create clean virtualenv
        run: |
          python -m venv venv
          venv\Scripts\activate
          python -m pip install --upgrade pip
          pip install pyinstaller requests

      - name: Build Windows binary
        run: |
          venv\Scripts\activate
          pyinstaller --onefile --add-binary "tools/windows/wg.exe;tools/windows" --add-binary "tools/windows/wg-quick.exe;tools/windows" main.py

      - name: Upload Windows binary
        uses: actions/upload-artifact@v4
        with:
          name: windows-binary
          path: dist/main-win.exe
